### ISSUE TITLE
Question: Is there a reason a dedicated PostgreSQL role is create for PostGraphile?

### ISSUE THREAD

**Issue by dancesWithCycles** [public-transport/gtfs-via-postgres#61]
Hi!
I notices a dedicated PostgreSQL role [`postgraphile`](https://github.com/public-transport/gtfs-via-postgres/blob/c5b28ec08159a07352579ade77a0c3f03956156b/index.js#L272) is created for PostGraphile. I wonder what is the reason? Can PostGraphile not use the PostgreSQL user that is used by the database connection anyways?

On my managed server the PostgreSQL user connected with the respective database holding the GTFS feed does NOT have the [CREATEROLE](https://www.postgresql.org/docs/current/sql-createrole.html) privilege and is NOT a database superuser.

Cheers!

**Comment by derhuerst** [comment]
[PostGraphile uses PostgreSQL roles to determine if unauthenticated & authenticated users (respectively) have read and/or write access.](https://postgraphile.org/postgraphile/current/default-role#roles-in-postgraphile) This is inherent in PostGraphile's design, so that it doesn't have to build another, bespoke authentication & authorisation mechanism on top.

[`gtfs-via-postgres` grants only read access to the `postgraphile` role](https://github.com/public-transport/gtfs-via-postgres/blob/df50320faca87d3861eab3b47919a489d7950128/index.js#L284-L288), so that the resulting GraphQL API is read-only.

> On my managed server the PostgreSQL user connected with the respective database holding the GTFS feed does NOT have the [CREATEROLE](https://www.postgresql.org/docs/current/sql-createrole.html) privilege and is NOT a database superuser.

I'm not sure how to combine this with PostGraphile's design. Maybe you could, after importing the data, drop all permissions on the database even for your single user – effectively making it read-only for everyone except admins – and let PostGraphile's use that single user (it will pickup `$DATABASE_URL`)?

**Comment by derhuerst** [comment]
I'm closing this. Please re-open if you have more questions about this.
